apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJRWEowVUhKdk9UcG5hSEJmY1c1TlRtMDNhMDFUT1ZkS1FuSlFVbGMzUzNOQldtbzJXVXR2ZFZjd01tcHpWRVo1Ig0KICAgIH0NCiAgfQ0KfQ==
type: kubernetes.io/dockerconfigjson
